import "./globals.css";

import Navbar from "-/components/Navbar";
import { ThemeProvider } from "-/components/providers/ThemeProvider";
import { cn } from "-/lib/utils";
import { Poppins } from "next/font/google";

import type { Metadata } from "next";
const fontSans = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Assignment Shuffler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.className,
          "antialiased min-h-screen flex flex-col"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
